### ISSUE TITLE
"raven" is a contested namespace

### ISSUE THREAD

**Issue by mas90** [danielrichman/python-ucam-webauth#9]
So, there's another Python package called "raven" (https://github.com/getsentry/raven-python), and that one is now packaged in Ubuntu and Debian as -- surprise -- "python-raven".  We have a namespace collision with both our Python package and our[*] Debian package.

I am assuming that the other raven is not likely to be amenable to vacating the namespace...

As it stands, if I simply published the existing package for recent Ubuntu/Debian releases, users would get the wrong raven when they upgrade their distribution.  There's no easy way out of this, I think -- all we can do is make backwards-incompatlble changes and/or break Ubuntu/Debian for people with our[*] Apt repository configured.

Regardless, it would be nice to let people use both ravens in their Python code, especially since they both integrate nicely with flask etc.!

I propose to do the following:

- Move our Python package "raven" into ucam_webauth.raven, keeping an *optional* backwards-compatible wrapper as "raven"
- Rename our Debian package to python-ucam-webauth (and python3-ucam-webauth), and exclude the compatibility wrapper
- Publish that Debian package in a brand new Apt repository so we can deprecate the old one that contains a namespace-colliding package
 - Separately package just the compatibility wrapper as python{,3}-raven (depending on python{,3}-ucam-webauth and published in its current repository), with an artificially high version number so that it supercedes the 'official' python-raven package when a user upgrades their distro to one with such a thing
- Stick a big warning on our python-raven package to inform the user that it will break anything that expects the other raven, and that they should tweak their code to use ucam_webauth.raven, switch Apt repositories and remove our python-raven package
- If feasible, try to add 'Conflicts' dependencies to our python-raven package for known users of the other python-raven, if there are any such packages in Ubuntu or Debian

Or alternatively (more disruptive to users but cleaner):

- Don't publish any packages in our existing Apt repository for distributions with their own python-raven
- Rename the Python and Debian packages as above, *without* providing a compatibility wrapper, published in a new Apt repository
- Users' distribution upgrades will break because the distribution being upgraded to doesn't exist in our repository
- Users have to figure out where the new package is by themselves
  - If users simply comment out our repository to "fix" the distribution upgrade, their code will break on upgrade because they will upgrade to the wrong raven -- this will almost certainly bite somebody, probably me
- Users have to change their code before they do a distribution upgrade

Thoughts welcome.  "I don't care about maintaining this any more" is valid, in which case I'll just fork and plough ahead. :-)

[*] By "our" Debian package and Apt repository I mean the de-facto one that I made and maintain... https://launchpad.net/~malcscott/+archive/ubuntu/python-raven -- that is my problem not yours, but I think we need to deal with renaming both at the same time.

**Comment by danielrichman** [comment]
python-raven was renamed to python-ucam-webauth and a compatibility repo and package python-raven that exports ucam_webauth.raven as raven was uploaded to pypi/etc.
